### ISSUE TITLE
Add toggle code button

### ISSUE THREAD

**Issue by mathieuboudreau** [Notebook-Factory/NeuralDecoding_book#6]
Following the same procedure as https://github.com/Notebook-Factory/BayesianRepetoireOverlap/issues/2 and https://github.com/Notebook-Factory/BayesianRepetoireOverlap/pull/4

@FilipVel have you started doing this update?

**Comment by FilipVel** [comment]
Yup I have done it [here](https://github.com/zelenkastiot/NeuralDecoding_book)
Should I merge it to this repo?

**Comment by mathieuboudreau** [comment]
Great! Open a pull request and I'll do a review of it before merging. Thanks!
