### ISSUE TITLE
Top of figure 5 is cut off

### ISSUE THREAD

**Issue by mathieuboudreau** [Notebook-Factory/NeuralDecoding_book#8]
See:

<img width="577" alt="Capture d’écran 2020-09-15 à 23 19 42" src="https://user-images.githubusercontent.com/1421029/93284891-0c3c4980-f7aa-11ea-9aed-04d770dc5c7e.png">

@FilipVel @zelenkastiot any clue why, and how to fix it?

**Comment by zelenkastiot** [comment]
Ahhhh tiny fix. Right on it

**Comment by zelenkastiot** [comment]
https://github.com/Notebook-Factory/NeuralDecoding_book/blob/master/_includes/js/print.html 

The margin has to be smaller, it was -8% changed it to -5%

**Comment by zelenkastiot** [comment]
Yeah so the margin in the [/includes/js/print](https://github.com/Notebook-Factory/NeuralDecoding_book/blob/master/_includes/js/print.html) has this lines: 

```Python
        el.style.zIndex = "0";
        el.style.marginTop = "-5%";
```

Changed the value of the top to: 

```Python
        el.style.zIndex = "0";
        el.style.marginTop = "-2%";
```

All the figures look great in my browser.

**Comment by zelenkastiot** [comment]
![image](https://user-images.githubusercontent.com/37374247/93309622-070be880-f804-11ea-9f3c-3093a93b9ff2.png)
