### ISSUE TITLE
Update PLOS logo

### ISSUE THREAD

**Issue by mathieuboudreau** [Notebook-Factory/NeuralDecoding_book#9]
The journal has requested that we update the logo to their new one:

![PLOS CB_color](https://user-images.githubusercontent.com/1421029/93355800-d5e7e400-f814-11ea-9627-ff13ad2074aa.png)

**Comment by zelenkastiot** [comment]
![image](https://user-images.githubusercontent.com/37374247/93357560-bcf52800-f840-11ea-8608-edb690acb267.png)
Doesn't look good...

This is my alternative option: 

![image](https://user-images.githubusercontent.com/37374247/93357741-f2017a80-f840-11ea-8ee0-2f48514349c2.png)

**Comment by zelenkastiot** [comment]
The one the journal uses is way to long

**Comment by zelenkastiot** [comment]
Or are you suggesting to edit the logo in the intro?

**Comment by zelenkastiot** [comment]
![image](https://user-images.githubusercontent.com/37374247/93359035-730d4180-f842-11ea-85fd-b9287ca4b0e2.png)
 
This is what you mean by the logo or the book logo?
